var words = {
	"spiteful": "malveillant",
	"stung": "blessé (émotion)",
	"brooding": "sombre",
	"pent-up": "accumulé",
	"ire": "colère provoquée",
	"incur": "subir",
	"hoggish": "avide",
	"wistfully": "avec nostalgie",
	"ensuing": "qui suit",
	"to be damned": "être fichu",
	"surefire": "infaillible",
	"off the table": "hors de question",
	"to kick the bucket": "passer l'arme à gauche",
	"moot": "discutable",
	"moist": "humide",
	"feverish": "fiévreux",
	"stifled": "étouffé",
	"to squirm": "se tortiller",
	"toddle": "trottiner",
	"crib": "berceaux",
	"cooed": "roucoulé",
	"cradled": "bercé",
	"to lurch": "tibuter",
	"frantically": "frénétiquement",
	"shuffle": "trainer des pieds",
	"mushy": "cucul",
	"to tend to someone": "s'occuper de",
	"clue": "idée",
	"cluttered": "encombré",
	"vicinity": "voisinage",
	"to exert": "exercer",
	"thereof": "de cela"
}
